config:
  target: "http://localhost:3000"
  phases:
    - duration: 60
      arrivalRate: 5
      name: Warm up
    - duration: 120
      arrivalRate: 5
      rampTo: 50
      name: Ramp up load
    - duration: 600
      arrivalRate: 50
      name: Sustained load

scenarios:
  # We define one scenario:
  - name: "get prod info for one product"
    flow:
      # Get the details of the product:
      - get:
          url: "/products/10000"

